In [ ]:
import numpy as np

arr1 = np.array([0,2,5.5,7])
print(arr1)

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[0.  2.  5.5 7. ]
[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.zeros((5,2))
print(type(arr))
print(arr.shape)
print(arr.dtype)
print(arr)

print("----------Start----------")
for i in range(5):
    print(arr[i, 1])
    arr[i, 1] = i
    print(arr[i, 1])
print("----------end----------")
print(arr)

<class 'numpy.ndarray'>
(5, 2)
float64
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
----------Start----------
0.0
0.0
0.0
1.0
0.0
2.0
0.0
3.0
0.0
4.0
----------end----------
[[0. 0.]
 [0. 1.]
 [0. 2.]
 [0. 3.]
 [0. 4.]]


In [ ]:
arr = np.empty((2,2), dtype=int)
print(arr.dtype)

arr = np.eye(3, k=-1)
print(arr)

int64
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
arr = np.arange(6)
print(arr)
arr1 = arr.reshape(3,2)
#arr1 = np.array([["a","c"],["b","d"]])
print(arr1)
#print(arr1.ravel("A"))
print(arr1.reshape(-1))
print(arr1.reshape(-1,1))
print(arr1.reshape(1,-1))

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
[0 1 2 3 4 5]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
[[0 1 2 3 4 5]]


In [ ]:
arr = np.arange(36).reshape(3,3,4)
print(arr[0:2])

arr = np.arange(12).reshape(3,4)
print(arr)
print(arr.ravel("C"))
print(arr.ravel("F"))


arr = np.arange(24).reshape(2,3,4)
print(arr)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.strides)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  4  8  1  5  9  2  6 10  3  7 11]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3
24
int64
8
(96, 32, 8)


In [ ]:
ex1 = np.dtype(np.int16)
print(ex1)
ex1 = np.dtype([('f1',np.int16)])
print(ex1)
ex1 = np.dtype([('f1',[('f1',np.int16)])])
print(ex1)

int16
[('f1', '<i2')]
[('f1', [('f1', '<i2')])]


In [ ]:
ex1 = np.dtype(np.int16)
print(ex1)
ex1 = np.dtype([('f1',np.int16)])
print(ex1)
ex1 = np.dtype([('f1',[('f1',np.int16)])])
print(ex1)

int16
[('f1', '<i2')]
[('f1', [('f1', '<i2')])]


In [ ]:
ex1 = np.dtype(np.int16)
print(ex1)
ex1 = np.dtype([('f1',np.int16)])
print(ex1)
ex1 = np.dtype([('f1',[('f1',np.int16)])])
print(ex1)
ex1 = np.dtype([('f1',np.uint),('f2',np.int32)])
print(ex1)
ex1 = np.dtype([('a','f8'),('b','S10')])
print(ex1)
ex1 = np.dtype([('i4','(2,3)f8')])
print(ex1)
ex1 = np.dtype([('hello',(int,3)),('world',np.void,10)])
print(ex1)
ex1 = np.dtype((np.int16,{'x':(np.int8,0), 'y':(np.int8,1)}))
print(ex1)
ex1 = np.dtype({'names':['gender','age'],'formats':['S1',np.uint8]})

int16
[('f1', '<i2')]
[('f1', [('f1', '<i2')])]
[('f1', '<u8'), ('f2', '<i4')]
[('a', '<f8'), ('b', 'S10')]
[('i4', '<f8', (2, 3))]
[('hello', '<i8', (3,)), ('world', 'V10')]
(numpy.int16, [('x', 'i1'), ('y', 'i1')])


In [ ]:
a = np.float32(5.0)
b = np.int_([1,2,3])
c = np.arange(5, dtype=np.uint16)
print(type(a))
print(type(b))
print(type(c))
print(b.dtype)
print(c.dtype)

dt = np.dtype('>i4')
print(dt.byteorder)
print(dt.name)
print(dt.itemsize)
print(dt.type is np.int32)

dt = np.dtype([('name',np.unicode_,16), ('grades', np.float64, (2,))])

print(dt)
print(dt['name'])
print(dt['grades'])

<class 'numpy.float32'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
int64
uint16
>
int32
4
True
[('name', '<U16'), ('grades', '<f8', (2,))]
<U16
('<f8', (2,))


In [ ]:
arr = np.array([('jin', 25, 67), ('suho', 18, 77)],
        dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
print(arr)
print(arr.dtype)

print(arr[1])
print(arr['age'])

[('jin', 25, 67.) ('suho', 18, 77.)]
[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')]
('suho', 18, 77.)
[25 18]


In [ ]:
arr = np.dtype('i8, f4, S3')
print(arr)

arr = np.dtype('3int8, float32, (2,3)float64')
print(arr)

arr = np.dtype({'names': ['col1', 'col2'], 'formats': ['i4', 'f4'],
                 'offsets': [0, 4], 'itemsize': 12})

print(arr)


c = np.dtype([('a', 'i8'), ('b', 'f4')])
print(c.names)
print(c.fields)

[('f0', '<i8'), ('f1', '<f4'), ('f2', 'S3')]
[('f0', 'i1', (3,)), ('f1', '<f4'), ('f2', '<f8', (2, 3))]
{'names':['col1','col2'], 'formats':['<i4','<f4'], 'offsets':[0,4], 'itemsize':12}
('a', 'b')
{'a': (dtype('int64'), 0), 'b': (dtype('float32'), 8)}


In [ ]:
def print_offsets(d):
    print("offsets:", [d.fields[name][1] for name in d.names])
    print("itemsize:", d.itemsize)

print_offsets(np.dtype('u1, u1, i4, u1, i8, u2'))
d = np.dtype('u1, u1, i4, u1, i8, u2')
print(d)
print(d.itemsize)
print(d.fields)
print(d.names)
print(d.fields['f0'])
print(d.fields['f0'][1])
print_offsets(np.dtype('u1, u1, i4, u1, i8, u2', align = True))

x = np.dtype([(('my title', 'name'), 'f4')])
print(x.fields)
print(x.names)

np.dtype({'name': ('i4', 0, 'my title')})

x = np.dtype({'name': ('i4', 0, 'my title')})

print(x.fields)
print(x.names)

offsets: [0, 1, 2, 6, 7, 15]
itemsize: 17
[('f0', 'u1'), ('f1', 'u1'), ('f2', '<i4'), ('f3', 'u1'), ('f4', '<i8'), ('f5', '<u2')]
17
{'f0': (dtype('uint8'), 0), 'f1': (dtype('uint8'), 1), 'f2': (dtype('int32'), 2), 'f3': (dtype('uint8'), 6), 'f4': (dtype('int64'), 7), 'f5': (dtype('uint16'), 15)}
('f0', 'f1', 'f2', 'f3', 'f4', 'f5')
(dtype('uint8'), 0)
0
offsets: [0, 1, 4, 8, 16, 24]
itemsize: 32
{'name': (dtype('float32'), 0, 'my title'), 'my title': (dtype('float32'), 0, 'my title')}
('name',)
{'name': (dtype('int32'), 0, 'my title'), 'my title': (dtype('int32'), 0, 'my title')}
('name',)


In [ ]:
a = np.array([(1, 2, 3), (4, 5, 6)], dtype='i8, f4, f8')
a[1] = ((7, 8, 9))
print(a)

a = np.zeros(2, dtype='i8, f4, ?, S1')
print(a)
a[:] = 7
print(a)
a[:] = np.arange(2)
print(a)

a = np.zeros(3, dtype=[('a', 'i8'), ('b', 'f4'), ('c', 'S3')])
b = np.ones(3, dtype=[('x', 'f4'), ('y', 'S3'), ('z', 'O')])
print(b)
b[:] = a
print(b)
print(a)

[(1, 2., 3.) (7, 8., 9.)]
[(0, 0., False, b'') (0, 0., False, b'')]
[(7, 7.,  True, b'7') (7, 7.,  True, b'7')]
[(0, 0., False, b'0') (1, 1.,  True, b'1')]
[(1., b'1', 1) (1., b'1', 1) (1., b'1', 1)]
[(0., b'0.0', b'') (0., b'0.0', b'') (0., b'0.0', b'')]
[(0, 0., b'') (0, 0., b'') (0, 0., b'')]


In [ ]:
arr1 = np.arange(10)
arr2 = np.arange(9).reshape(3,3)
arr3 = np.reshape(np.arange(24),(2,3,4))

print(arr1)
print(arr1[1])
print(arr2)
print(arr2[2])
print(arr2[2,1])
print(arr3)
print(arr3[1,1,2])
print(arr3[1][2][3])

[0 1 2 3 4 5 6 7 8 9]
1
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[6 7 8]
7
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
18
23


In [ ]:
print(arr1[1])
print(arr1[:6])
print(arr1[0:5])
print(arr1[::2])
print(arr1[1::2])
print(arr1[1:7:2])



#[0 1 2 3 4 5 6 7 8 9]


print(arr1[-3:9])
print(arr1[:-3])
print(arr1[-3:2:-1])

print(arr1[5:2])

print(arr1[5:])
print(arr2[1:])

print(arr2)
print(arr2[:2, :2])
print(arr2[:, ::-1])

print(arr2[:, :])
print(arr2[1, :])
print(arr2[1, 2])

print(arr3[:2, 1:, :2])


1
[0 1 2 3 4 5]
[0 1 2 3 4]
[0 2 4 6 8]
[1 3 5 7 9]
[1 3 5]
[7 8]
[0 1 2 3 4 5 6]
[7 6 5 4 3]
[]
[5 6 7 8 9]
[[3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1]
 [3 4]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[3 4 5]
5
[[[ 4  5]
  [ 8  9]]

 [[16 17]
  [20 21]]]


In [ ]:
print("---------------------------")

arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr)
print(arr[[0, 1, 2], [0, 1, 0]])
print(np.array([arr[0,0], arr[1,1], arr[2,0]]))

arr = np.array([[0,   1,   2], [3,   4,   5], [6,   7,   8], [9,  10,  11]])
rows = np.array([[0, 0], [3, 3]], dtype=np.intp)
columns = np.array([[0, 2], [0, 2]], dtype=np.intp)
print(arr)
print(arr[rows, columns])

---------------------------
[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[1 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  2]
 [ 9 11]]


In [ ]:
print(arr[rows[:, np.newaxis], columns])
print(np.newaxis is None)
arr = np.arange(25).reshape(5, 5)
print(arr.shape)
arr_3d = arr[np.newaxis]
print(arr_3d.shape)

arr = np.arange(10)
print(arr.shape)
arr_row = arr[np.newaxis, :]
print(arr_row.shape)
arr_col = arr[:, np.newaxis]
print(arr_col.shape)


arr = np.array([[0,   1,   2],
                 [3,   4,   5],
                 [6,   7,   8],
                 [9,  10,  11]])
rows = np.array([0, 3], dtype=np.intp)
columns = np.array([0, 2], dtype=np.intp)
print(rows[:, np.newaxis])
print(arr[rows[:, np.newaxis], columns])
print(rows[:, np.newaxis], columns)


[[[ 0  2]
  [ 0  2]]

 [[ 9 11]
  [ 9 11]]]
True
(5, 5)
(1, 5, 5)
(10,)
(1, 10)
(10, 1)
[[0]
 [3]]
[[ 0  2]
 [ 9 11]]
[[0]
 [3]] [0 2]


In [ ]:
arr1= np.array([1, 2, 3, 4, 5])
arr2 = np.array([11, 12, 13])
arr1_nx = arr1[:, np.newaxis]
arr2_nx = arr2[:, np.newaxis]
print(arr1_nx)
print(arr2_nx)
print(arr1_nx + arr2)
print(arr2_nx + arr1)


arr = np.arange(10).reshape(2, 5)
print(arr)
ix_ms = np.ix_([0, 1], [2, 4])
print(ix_ms)
print(ix_ms[0].shape, ix_ms[1].shape)
print(arr[ix_ms])



ix_ms = np.ix_([True, True], [2, 4])
print(ix_ms)
print(arr[ix_ms])
ix_ms = np.ix_([True, True], [False, False, True, False, True])
print(ix_ms)

print(arr[ix_ms])

[[1]
 [2]
 [3]
 [4]
 [5]]
[[11]
 [12]
 [13]]
[[12 13 14]
 [13 14 15]
 [14 15 16]
 [15 16 17]
 [16 17 18]]
[[12 13 14 15 16]
 [13 14 15 16 17]
 [14 15 16 17 18]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
(array([[0],
       [1]]), array([[2, 4]]))
(2, 1) (1, 2)
[[2 4]
 [7 9]]
(array([[0],
       [1]]), array([[2, 4]]))
[[2 4]
 [7 9]]
(array([[0],
       [1]]), array([[2, 4]]))
[[2 4]
 [7 9]]


In [ ]:

arr = np.arange(12).reshape(3,4)
ind = arr>5
print(ind)
print(ind[:,1])
print(arr[ind[:,1]])


arr = np.array([[1, 0, 0], [0, 2, 0], [1, 1, 0]])
print(arr)
print(np.nonzero(arr))
print(np.transpose(np.nonzero(arr)))
print(arr[np.nonzero(arr)])

arr = np.arange(9).reshape(3,3)
print(arr > 3)
print(np.nonzero(arr > 3))
print((arr > 3).nonzero())


arr = np.arange(4).reshape((2, 2))
print(arr)
print(np.transpose(arr))
arr1 = np.ones((1, 2, 3))
print(np.transpose(arr1, (1, 0, 2)).shape)

a = [1, 2, 3]
b = np.array(a)
print(b)
print(b.transpose())
arr = np.array([a])
print(arr.T)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[False False  True]
[[ 8  9 10 11]]
[[1 0 0]
 [0 2 0]
 [1 1 0]]
(array([0, 1, 2, 2]), array([0, 1, 0, 1]))
[[0 0]
 [1 1]
 [2 0]
 [2 1]]
[1 2 1 1]
[[False False False]
 [False  True  True]
 [ True  True  True]]
(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))
(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))
[[0 1]
 [2 3]]
[[0 2]
 [1 3]]
(2, 1, 3)
[1 2 3]
[1 2 3]
[[1]
 [2]
 [3]]
