In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
documents = []
for i in range(10):
    i = str(i+1)
    r = open('/content/gdrive/My Drive/2022-1 빅데이터 통계분석/뉴스'+i+'.txt', mode='r')
    text = r.read()
    r.close()
    documents.append(text)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
import numpy as np
import matplotlib.pyplot as plt
plt.rc('font', family='NanumBarunGothic')
!pip install konlpy 
from konlpy.tag import Komoran

komoran = Komoran()
documents_preprocessed = [' '.join(komoran.nouns(text)) for text in documents]

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 19.4 MB 4.9 MB/s 
     |████████████████████████████████| 453 kB 57.7 MB/s 


In [ ]:
nouns = [komoran.nouns(text) for text in documents]
noun = []
for i, v in enumerate(nouns):
      for n in v:
          if len(n)>1:
              noun.append(n)
print(noun)

['러시아 국방부', '우크라이나', '가담', '참전', '한국인', '러시아 국방부', '현지', '시간', '우크라이나', '외국', '용병', '현황', '자료', '한국', '국적', '우크라이나', '사망', '우크라이나', '우크라이나', '입출국', '자와', '사망자', '잔류', '숫자', '이상', '내용', '공개', '외교부', '러시아 국방부', '공개', '자료', '확보', '사실', '관계', '확인', '4월', '정부', '의용군', '참가', '국민', '사망자', '첩보', '입수', '현재', '사망자', '확인', '정부', '여행', '금지', '조치', '우크라이나', '무단', '출국', '현지', '의용군', '참여', '이근', '해군', '특수', '전단', '대위', '지난달', '귀국', '현재', '우크라이나', '국제', '용구', '개국', '추정', '외신', '현지', '시간', '존슨', '총리', '이우', '로디', '미르', '렌스', '우크라이나', '대통령', '회담', '공동', '기자회견', '우크라이나', '전폭', '의사', '재확인', '존슨', '총리', '이우', '방문', '2월', '러시아', '우크라이나', '침공', '이후', '4월', '이우', '렌스', '대통령', '거리', '걷기', '존슨', '총리', '오늘', '방문', '메시지', '궁극', '승리', '존슨', '총리', '보궐', '선거', '다음', '주인', '이날', '행사', '참석', '일정', '취소', '이우', '방문', '유럽', '출장', '귀국', '이재용', '삼성전자', '부회장', '현지', '우크라이나', '전쟁', '여파', '실감', '기술', '기술', '기술', '강조', '지정학', '위기', '봉쇄', '여파', '가중', '글로벌', '경기', '침체', '우려', '돌파', '근본', '해법', '격차', '기술', '경쟁력', '풀이', '이날', '오전'

In [ ]:
count_vectorizer = CountVectorizer(min_df=3)
feat_vect = count_vectorizer.fit_transform(documents_preprocessed)
feature_names = count_vectorizer.get_feature_names_out()
print('단어 목록:', feature_names)
print('문서단어행렬 모양 (문서의 수, 단어의 수):', feat_vect.shape)
print(feat_vect.toarray())

단어 목록: ['가격' '가치' '경기' '글로벌' '기록' '기준' '러시아' '물가' '미국' '비트코인' '상승' '시간' '시장' '오후'
 '우려' '우크라이나' '위기' '위축' '이날' '이후' '있다' '전망' '정부' '침공' '투자' '현지' '화폐']
문서단어행렬 모양 (문서의 수, 단어의 수): (10, 27)
[[0 0 0 0 0 0 3 0 0 0 0 1 0 0 0 7 0 0 0 0 0 0 2 0 0 2 0]
 [0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 3 0 0 1 1 0 0 0 1 0 1 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 2 1 0 1 0 0 0 0 0 0 1 0]
 [0 1 0 0 0 1 1 0 0 0 0 1 0 0 0 4 0 0 0 1 1 0 0 1 0 1 0]
 [3 1 2 1 1 0 0 0 0 7 0 0 1 1 2 0 1 1 0 1 0 1 0 0 1 0 2]
 [3 0 0 0 1 1 0 1 3 3 1 2 2 1 0 0 0 1 0 1 0 1 0 0 1 0 4]
 [1 1 0 0 2 1 0 0 0 7 0 1 0 0 0 0 0 0 1 0 0 0 2 0 2 1 1]
 [1 0 1 0 0 0 0 2 0 0 0 0 1 1 1 1 1 1 1 0 3 0 3 0 2 0 0]
 [0 0 0 0 1 0 0 3 3 0 2 1 0 0 1 0 0 0 1 0 1 1 0 0 0 1 0]
 [2 0 0 2 0 0 1 2 2 0 1 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0]]


In [ ]:
lda = LatentDirichletAllocation(n_components=3)
lda.fit(feat_vect)

LatentDirichletAllocation(n_components=3)

In [ ]:
topic_word_dist = lda.components_ / lda.components_.sum(axis=1)[:, np.newaxis]
doc_topic_dist = lda.transform(feat_vect)

In [ ]:
print(doc_topic_dist[2,:])

[0.34287589 0.62002713 0.03709698]


In [ ]:
sorted_topic_dist = np.argsort(topic_word_dist[0,:])
topic_words = np.array(feature_names)[sorted_topic_dist]
topic_probs = np.array(topic_word_dist[0,:])[sorted_topic_dist]
topic_words = topic_words[:-3:-1]
topic_probs = topic_probs[:-3:-1]
print('중요 단어 1: {}    중요 단어 1의 확률: {}\n중요 단어 2: {}    중요 단어 2의 확률: {}\n'.
      format(topic_words[0], round(topic_probs[0],4), topic_words[1], round(topic_probs[1],4)))

중요 단어 1: 우크라이나    중요 단어 1의 확률: 0.3496
중요 단어 2: 러시아    중요 단어 2의 확률: 0.1206

